# Custom Language File for Launcher Customizer

[ejs.app]
title = "럭키블럭 켠왕"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/Unible"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/Unible"
supportLink = "https://github.com/mchlauncher/Unible/issues"

[ejs.welcome]
welcomeHeader = "럭키블럭 켠왕"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."